[[main]]
  name = 'nav_about'
  pageRef = '/about'
  weight = 10

[[main]]
  name = 'nav_research'
  pageRef = '/research'
  weight = 20

[[main]]
  name = 'nav_projects'
  pageRef = '/projects'
  weight = 30

[[main]]
  name = 'nav_publications'
  pageRef = '/publications'
  weight = 40

[[main]]
  name = 'nav_resources'
  pageRef = '/resources'
  weight = 50

[[main]]
  name = 'nav_team'
  pageRef = '/team'
  weight = 60
